GET http://localhost:5000/notes

### READ
GET http://localhost:5000//notes/1

### CREATE
POST http://localhost:5000/add-notes
Content-Type: application/json

{
    "title": "Test Cloud",
    "content": "Berhasil migrasi DB ke cloud"
}

### UPDATE
PUT http://localhost:5000/edit-notes/3
Content-Type: application/json

{
    "title": "Shell Better Than Pertamina",
    "content": "Shell adalah perusahaan minyak dan gas asal Belanda yang berdiri sejak tahun 1907. Shell memiliki kualitas bensin yang lebih baik daripada Pertamina. Namun sayangnya di Jogja tidak ada SPBU Shell" 
}

### DELETE
DELETE http://localhost:5000/delete-notes/4
```